name: check

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      if: matrix.os == 'ubuntu-latest'
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
    - name: Install Rust
      if: matrix.os == 'windows-latest'
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        target: x86_64-pc-windows-msvc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
